apiVersion: v1
kind: Namespace
metadata:
  name: tripsync
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tripsync-config
  namespace: tripsync
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  TOUR_SERVICE_URL: "http://tour-service:3000"
  PROPERTY_SERVICE_URL: "http://property-service:8081"
  CAR_SERVICE_URL: "http://car-service:8082"
  BOOKING_SERVICE_URL: "http://booking-service:8083"
---
apiVersion: v1
kind: Secret
metadata:
  name: tripsync-secrets
  namespace: tripsync
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "TripsyncR00t!Secret"
  JWT_SECRET: "change-me-please-32-characters-minimum"
  REDIS_PASSWORD: "TripsyncRedis!Secret"
  VAULT_TOKEN: "tripsync-root-token"
  DATABASE_URL_TOUR: "postgresql://postgres:TripsyncR00t!Secret@postgres:5432/tripsync_db?schema=public"
