input {
  beats {
    port => 5000
  }
  tcp {
    port => 5001
    codec => json_lines
  }
}

filter {
  if [message] =~ /^\{.*\}$/ {
    json {
      source => "message"
    }
  }
  mutate {
    add_field => { "[@metadata][index]" => "tripsync-logs-%{+YYYY.MM.dd}" }
  }
}

output {
  elasticsearch {
    hosts => ["${ELASTICSEARCH_HOST}:9200"]
    index => "tripsync-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
